### PR TITLE
Fix #20: use jar as input file

### LINKED ISSUE #20: Always UP-TO-DATE after 1st build
The ikvm task is always "UP-TO-DATE" after the first run and will never rebuild the assembly when modifying or adding java files. Even if the jar task executes the ikvm task will not. I notice when I delete the debug (*.pdb file) then the ikvm task will run. Something must be misconfigured with the ikvm task inputs. I looked an Ikvm.groovy and didn't see anything glaringly wrong.

### PR DESCRIPTION
**Pull request by jpenglert**

### CODE REVIEW

File: src/main/groovy/com/ullink/Ikvm.groovy [hunk 1]
```diff
@@ -123,7 +123,12 @@ class Ikvm extends ConventionTask {
             return project.file(getKeyFile())
         }
         return new File[0]
-    } 
+    }
+
+    @InputFiles
```
Comment (gluck) [inline src/main/groovy/com/ullink/Ikvm.groovy]: `InputFile` will be just fine no ? this is no collection AFAIK

File: src/main/groovy/com/ullink/Ikvm.groovy [hunk 2]
```diff
@@ -123,7 +123,12 @@ class Ikvm extends ConventionTask {
...
+    def getJar() {
```
Comment (gluck) [inline src/main/groovy/com/ullink/Ikvm.groovy]: maybe you can also reuse this getter below in build method instead of archivePath (for consistency) ?

File: src/main/groovy/com/ullink/Ikvm.groovy (hunk 1 above)
Comment (jpenglert) [inline src/main/groovy/com/ullink/Ikvm.groovy]: Yep, good catch

File: src/main/groovy/com/ullink/Ikvm.groovy (hunk 2 above)
Comment (jpenglert) [inline src/main/groovy/com/ullink/Ikvm.groovy]: Don't see why not. Done.
